// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crux/iam/v1/authorization.proto

package iampb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AuthorizationData struct {
	// The other authorization which has been authorized to represent the this
	// this authorization.
	AssumingAuthorization *AuthorizationData `protobuf:"bytes,1,opt,name=assuming_authorization,json=assumingAuthorization,proto3" json:"assuming_authorization,omitempty"`
	// Authorization ID is an identifier of an authorization. It's
	// unique within the system. It's a session identifier.
	AuthorizationId string `protobuf:"bytes,2,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	// The expiry time of this authorization. Clients are recommended to refresh
	// the authorization before current authorization expired (~1 minute before
	// expired).
	ExpiryTime *types.Timestamp `protobuf:"bytes,3,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	// The ID of the user who granted this authorization, if any.
	SubjectUserId string `protobuf:"bytes,4,opt,name=subject_user_id,json=subjectUserId,proto3" json:"subject_user_id,omitempty"`
}

func (m *AuthorizationData) Reset()         { *m = AuthorizationData{} }
func (m *AuthorizationData) String() string { return proto.CompactTextString(m) }
func (*AuthorizationData) ProtoMessage()    {}
func (*AuthorizationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_41958c4de574fa98, []int{0}
}
func (m *AuthorizationData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorizationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorizationData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorizationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationData.Merge(m, src)
}
func (m *AuthorizationData) XXX_Size() int {
	return m.Size()
}
func (m *AuthorizationData) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationData.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationData proto.InternalMessageInfo

func (m *AuthorizationData) GetAssumingAuthorization() *AuthorizationData {
	if m != nil {
		return m.AssumingAuthorization
	}
	return nil
}

func (m *AuthorizationData) GetAuthorizationId() string {
	if m != nil {
		return m.AuthorizationId
	}
	return ""
}

func (m *AuthorizationData) GetExpiryTime() *types.Timestamp {
	if m != nil {
		return m.ExpiryTime
	}
	return nil
}

func (m *AuthorizationData) GetSubjectUserId() string {
	if m != nil {
		return m.SubjectUserId
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthorizationData)(nil), "crux.iam.v1.AuthorizationData")
}

func init() { proto.RegisterFile("crux/iam/v1/authorization.proto", fileDescriptor_41958c4de574fa98) }

var fileDescriptor_41958c4de574fa98 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x3f, 0x4b, 0xc3, 0x40,
	0x18, 0xc6, 0x73, 0x2a, 0x82, 0x17, 0xa4, 0x1a, 0x50, 0x42, 0x87, 0x6b, 0x71, 0x90, 0x3a, 0xe4,
	0x8e, 0xea, 0xd8, 0x49, 0x11, 0xa4, 0x6b, 0xb0, 0x8b, 0x4b, 0xb8, 0x24, 0x67, 0x7a, 0xe2, 0xf5,
	0xc2, 0xfd, 0x29, 0xb5, 0x9f, 0xc2, 0x8f, 0xe5, 0xd8, 0xd1, 0x51, 0x92, 0x6f, 0xe1, 0x24, 0x49,
	0x0c, 0x24, 0x74, 0x7d, 0xde, 0xe7, 0x7d, 0x7f, 0xcf, 0xc3, 0x0b, 0x47, 0x89, 0xb2, 0x1b, 0xc2,
	0xa9, 0x20, 0xeb, 0x29, 0xa1, 0xd6, 0x2c, 0xa5, 0xe2, 0x5b, 0x6a, 0xb8, 0x5c, 0xe1, 0x5c, 0x49,
	0x23, 0x3d, 0xb7, 0x32, 0x60, 0x4e, 0x05, 0x5e, 0x4f, 0x87, 0xa3, 0x4c, 0xca, 0xec, 0x9d, 0x91,
	0x7a, 0x14, 0xdb, 0x57, 0x62, 0xb8, 0x60, 0xda, 0x50, 0x91, 0x37, 0xee, 0xab, 0x5f, 0x00, 0xcf,
	0xef, 0xbb, 0x57, 0x1e, 0xa9, 0xa1, 0xde, 0x02, 0x5e, 0x52, 0xad, 0xad, 0xe0, 0xab, 0x2c, 0xea,
	0x31, 0x7c, 0x30, 0x06, 0x13, 0xf7, 0x16, 0xe1, 0x0e, 0x04, 0xef, 0xed, 0x87, 0x17, 0xed, 0x76,
	0x6f, 0xe4, 0xdd, 0xc0, 0xb3, 0xde, 0xb5, 0x88, 0xa7, 0xfe, 0xc1, 0x18, 0x4c, 0x4e, 0xc2, 0x41,
	0x4f, 0x9f, 0xa7, 0xde, 0x0c, 0xba, 0x6c, 0x93, 0x73, 0xf5, 0x11, 0x55, 0x89, 0xfd, 0xc3, 0x1a,
	0x3b, 0xc4, 0x4d, 0x1d, 0xdc, 0xd6, 0xc1, 0xcf, 0x6d, 0x9d, 0x10, 0x36, 0xf6, 0x4a, 0xf0, 0xae,
	0xe1, 0x40, 0xdb, 0xf8, 0x8d, 0x25, 0x26, 0xb2, 0x9a, 0xa9, 0x0a, 0x73, 0x54, 0x63, 0x4e, 0xff,
	0xe5, 0x85, 0x66, 0x6a, 0x9e, 0x3e, 0x3c, 0x7d, 0x15, 0x08, 0xec, 0x0a, 0x04, 0x7e, 0x0a, 0x04,
	0x3e, 0x4b, 0xe4, 0xec, 0x4a, 0xe4, 0x7c, 0x97, 0xc8, 0x79, 0x09, 0x32, 0x6e, 0x96, 0x36, 0xc6,
	0x89, 0x14, 0x44, 0xb1, 0x6d, 0x90, 0x49, 0x52, 0x35, 0x0e, 0x68, 0xce, 0x35, 0xe9, 0x7c, 0x60,
	0xc6, 0xa9, 0xc8, 0xe3, 0xf8, 0xb8, 0x0e, 0x74, 0xf7, 0x17, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x3a,
	0xb2, 0xf7, 0x9d, 0x01, 0x00, 0x00,
}

func (m *AuthorizationData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorizationData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorizationData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SubjectUserId) > 0 {
		i -= len(m.SubjectUserId)
		copy(dAtA[i:], m.SubjectUserId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.SubjectUserId)))
		i--
		dAtA[i] = 0x22
	}
	if m.ExpiryTime != nil {
		{
			size, err := m.ExpiryTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthorization(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AuthorizationId) > 0 {
		i -= len(m.AuthorizationId)
		copy(dAtA[i:], m.AuthorizationId)
		i = encodeVarintAuthorization(dAtA, i, uint64(len(m.AuthorizationId)))
		i--
		dAtA[i] = 0x12
	}
	if m.AssumingAuthorization != nil {
		{
			size, err := m.AssumingAuthorization.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthorization(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuthorization(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthorization(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AuthorizationData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssumingAuthorization != nil {
		l = m.AssumingAuthorization.Size()
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.AuthorizationId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	if m.ExpiryTime != nil {
		l = m.ExpiryTime.Size()
		n += 1 + l + sovAuthorization(uint64(l))
	}
	l = len(m.SubjectUserId)
	if l > 0 {
		n += 1 + l + sovAuthorization(uint64(l))
	}
	return n
}

func sovAuthorization(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthorization(x uint64) (n int) {
	return sovAuthorization(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AuthorizationData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorizationData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorizationData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssumingAuthorization", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AssumingAuthorization == nil {
				m.AssumingAuthorization = &AuthorizationData{}
			}
			if err := m.AssumingAuthorization.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiryTime == nil {
				m.ExpiryTime = &types.Timestamp{}
			}
			if err := m.ExpiryTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubjectUserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthorization
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubjectUserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthorization(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthorization
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthorization
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthorization
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthorization
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthorization
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthorization        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthorization          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthorization = fmt.Errorf("proto: unexpected end of group")
)
